# SPDX-FileCopyrightText: 2019 Free Software Foundation Europe e.V. <https://fsfe.org>
# SPDX-FileCopyrightText: 2022 Carmen Bianca Bakker <carmenbianca@fsfe.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Docker

on:
  push:
    # Tags will carry the tag's version, e.g. v1.2.3:
    # - 1.2.3
    # - 1.2
    # - 1 (not with 0 though)
    # - latest"
    tags:
      - "v*.*.*"
  # On PRs only do tests
  pull_request:

jobs:
  # ===========================================================================
  # Test Docker images
  # ===========================================================================
  docker_test:
    name: Test the Docker images
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      # Dockerfile
      - name: Build Dockerfile
        run: |
          docker build -t reuse -f Dockerfile .
      - name: Run Docker image
        run: |
          docker run -v "$(pwd):/data" reuse
      # Dockerfile-debian
      - name: Build Dockerfile-debian
        run: |
          docker build -t reuse-debian -f Dockerfile-debian .
      - name: Run Docker debian image
        run: |
          docker run -v "$(pwd):/data" reuse-debian

  # ===========================================================================
  # Build and push Docker images for tagged releases
  # ===========================================================================
  docker_push_tag:
    name: Push Docker images for tags to Docker Hub
    runs-on: ubuntu-24.04
    # Depends on successful Docker build/test
    needs:
      - docker_test
    if:
      ${{ github.event_name != 'pull_request' && startsWith(github.ref,
      'refs/tags/v') }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Dockerfile
      - name: Alpine Docker - set metadata
        id: meta_default
        uses: docker/metadata-action@v3
        with:
          images: fsfe/reuse
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
      - name: Alpine docker - build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta_default.outputs.tags }}
          labels: ${{ steps.meta_default.outputs.labels }}

      # Dockerfile-debian
      - name: Debian Docker - set metadata
        id: meta_debian
        uses: docker/metadata-action@v3
        with:
          images: fsfe/reuse
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
          flavor: |
            suffix=-debian,onlatest=true
      - name: Debian Docker - build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-debian
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta_debian.outputs.tags }}
          labels: ${{ steps.meta_debian.outputs.labels }}
